import asyncio
import pandas as pd
import logging
from iqclient import IQOptionAPI
from strategies import analyze_strategy
from ml_utils import prepare_features
import numpy as np

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

async def collect_and_label_data(api, asset, count=5000, timeframe=60):
    """
    Fetches data, runs the strategy to find signals, and labels them (Win/Loss).
    """
    logger.info(f"Fetching {count} candles for {asset}...")
    
    
    # Chunking Logic to fetch deep history
    candles = []
    chunk_size = 1000
    current_end_time = None # Start from "now"
    
    remaining = count
    
    while remaining > 0:
        fetch_size = min(chunk_size, remaining)
        # We generally fetch max chunk size (1000) to be safe with IQ API limits, 
        # even if we need less, to ensure continuity.
        fetch_size = 1000 
        
        logger.info(f"Fetching chunk... (Remaining: {remaining})")
        
        try:
            chunk = api.get_candle_history(asset, fetch_size, timeframe, end_time=current_end_time)
        except Exception as e:
            logger.error(f"Error fetching chunk: {e}")
            break
            
        if not chunk:
            logger.warning("No more candles received.")
            break
            
        # IQ Option returns old -> new. 
        # Prepend to our list (since we are going backwards in time)
        # OR: Append appropriately.
        # If we fetch older chunks, we should collect them and then sort/merge.
        # Simplest: Collect all chunks, then sort by time.
        
        candles.extend(chunk)
        
        # Update end_time for next batch: The oldest candle's time (first in list)
        oldest_time = chunk[0]['from']
        current_end_time = oldest_time
        
        remaining -= len(chunk)
        # Avoid infinite loop if API keeps returning same data or something
        if len(chunk) < 5: 
           break
           
    # Post-process: Deduplicate and sort
    # Convert to DataFrame
    df = pd.DataFrame(candles)
    if df.empty:
        logger.error("No candles received after fetching.")
        return None
        
    df = df.drop_duplicates(subset=['from'])
    df = df.sort_values(by='from').reset_index(drop=True)
    
    cols = ['open', 'close', 'min', 'max', 'volume']
    for c in cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c])
            
    if 'from' in df.columns:
        df['time'] = pd.to_datetime(df['from'], unit='s')
        
    # --- 1. Prepare Features (RSI, Bollinger, etc.) ---
    df_features = prepare_features(df)
    
    # Use localized WMA function for vectorization
    def wma_series(series, period):
         return series.rolling(period).apply(
            lambda x: ((x * np.arange(1, period + 1)).sum()) / np.arange(1, period + 1).sum(), 
            raw=True
        )

    # --- Vectorized Strategy Logic ---
    # Signals are now generated inside prepare_features(df)
    
    # Initialize Signal Column
    df_features['signal'] = None
    
    # Use columns generated by ml_utils.prepare_features
    # Ensure they exist (calculated in prepare_features)
    mask_call = (df_features['amiq_call'] == 1) | (df_features['sniper_call'] == 1)
    mask_put = (df_features['amiq_put'] == 1) | (df_features['sniper_put'] == 1)
    
    df_features.loc[mask_call, 'signal'] = "CALL"
    df_features.loc[mask_put, 'signal'] = "PUT"
    
    # --- Vectorized Filters ---
    # EMA 200
    if 'ema_200' not in df_features.columns:
        df_features['ema_200'] = df_features['close'].ewm(span=200, adjust=False).mean()
    
    # RSI
    # prepare_features already adds 'rsi'
    
    # Apply Filters
    # Filter CALLs: Block if RSI > 70 or Close < EMA200
    mask_block_call = (df_features['signal'] == "CALL") & ((df_features['rsi'] > 70) | (df_features['close'] < df_features['ema_200']))
    df_features.loc[mask_block_call, 'signal'] = None
    
    # Filter PUTs: Block if RSI < 30 or Close > EMA200
    mask_block_put = (df_features['signal'] == "PUT") & ((df_features['rsi'] < 30) | (df_features['close'] > df_features['ema_200']))
    df_features.loc[mask_block_put, 'signal'] = None
    
    # --- Use Vectorized Signals for Labeling ---
    # We only care about rows where signal is NOT None
    signal_rows = df_features[df_features['signal'].notna()].copy()
    
    labeled_data = []
    
    # Iterate only over signal rows to determine outcome
    # Check outcome on NEXT candle (shift(-1) could work but let's be careful with indices)
    # Ideally: Outcome is based on next candle's Close vs Open.
    
    # We need access to the *next* candle. signal_rows is a filtered view, so we can't just shift(-1).
    # We need to map back to original index or use original DF logic.
    
    # Logic:
    # 1. Identify indices with signals
    # 2. For each index `idx`, check `df_features.loc[idx+1]` (or appropriate time-based lookahead)
    
    valid_indices = signal_rows.index
    max_idx = df_features.index.max()
    
    for idx in valid_indices:
        if idx + 1 > max_idx:
            continue
            
        entry_candle = df_features.loc[idx]
        next_candle = df_features.loc[idx+1]
        
        sig = entry_candle['signal']
        
        is_win = False
        if sig == "CALL":
            is_win = next_candle['close'] > next_candle['open']
        elif sig == "PUT":
            is_win = next_candle['close'] < next_candle['open']
            
        row = entry_candle.copy()
        row['outcome'] = 1 if is_win else 0
        
        # Clean up utility columns if desired, or keep them
        labeled_data.append(row)

    if not labeled_data:
        logger.warning(f"No signals found in {len(df)} candles.")
        return None
        
    logger.info(f"Found {len(labeled_data)} training examples.")
    return pd.DataFrame(labeled_data)

async def main():
    api = IQOptionAPI()
    await api._connect()
    
    # Choose Market Type to collect
    # OTC_ASSETS = ["EURUSD-OTC", "USDJPY-OTC", "GBPUSD-OTC"]
    # REAL_ASSETS = ["EURUSD", "GBPUSD", "USDJPY", "EURJPY"]
    
    market_type = "real" # Change to "real" for Real market data
    assets = ["EURUSD-OTC", "USDJPY-OTC", "GBPUSD-OTC"] if market_type == "otc" else ["EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "EURJPY"]
    
    all_data = []
    
    for asset in assets:
        # Increase count for better generalization
        df = await collect_and_label_data(api, asset, count=20000)
        if df is not None:
             df['asset'] = asset
             all_data.append(df)
    
    if all_data:
        final_df = pd.concat(all_data, ignore_index=True)
        filename = f"training_data_{market_type}.csv"
        final_df.to_csv(filename, index=False)
        logger.info(f"Saved {len(final_df)} total records to {filename}")
        
        # Optionally trigger training automatically
        from ml_utils import train_model
        train_model(filename, market_type)
    else:
        logger.error("Failed to collect any data.")

if __name__ == "__main__":
    asyncio.run(main())
